import {
  AlarmClock,
  Amphora,
  Apple,
  Baby,
  Backpack,
  BatteryCharging,
  Bean,
  BedDouble,
  Beef,
  Bike,
  Blocks,
  BookOpen,
  BrushCleaning,
  CakeSlice,
  Camera,
  CarFront,
  Carrot,
  ChefHat,
  Clock,
  Coffee,
  CookingPot,
  Croissant,
  Crown,
  CupSoda,
  Diamond,
  Droplets,
  Drumstick,
  Dumbbell,
  Egg,
  Fan,
  Fish,
  FishingRod,
  Flame,
  Flower2,
  Footprints,
  Frame,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Handbag,
  Headphones,
  HeartPulse,
  Hourglass,
  Lamp,
  Laptop,
  Luggage,
  Mars,
  Milk,
  NotebookPen,
  Nut,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  PencilRuler,
  Percent,
  Pill,
  PillBottle,
  Plug,
  Popcorn,
  Puzzle,
  Scissors,
  Shirt,
  ShoppingBasket,
  Smartphone,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  Sparkles,
  Spool,
  Sprout,
  Star,
  Tablet,
  Tag,
  Tent,
  Timer,
  ToyBrick,
  Tv,
  Utensils,
  Venus,
  Volleyball,
  WashingMachine,
  Watch,
  Wheat,
  Wrench,
} from "lucide-react";

// Curated Category icon library (lucide-react, named imports only — never the
// whole set). Keys are Storvia's own stable kebab-case names, stored in
// Category.iconKey; a Lucide rename only changes an import here.
// To add an icon, add it to this file in BOTH storvia-admin and
// storvia-storefront; the two copies must stay byte-identical.

export const CATEGORY_ICON_GROUPS = [
  "Fashion",
  "Watches & jewellery",
  "Grocery & kitchen",
  "Home",
  "Electronics",
  "Beauty & health",
  "Kids & baby",
  "Sports & outdoors",
  "General",
] as const;

export type CategoryIconGroup = (typeof CATEGORY_ICON_GROUPS)[number];

export const CATEGORY_ICONS = {
  // Fashion
  "clothing": { icon: Shirt, label: "Clothing", group: "Fashion", keywords: ["tops", "apparel", "tshirt", "shirts", "kurta", "shalwar kameez", "dresses"] },
  "mens-fashion": { icon: Mars, label: "Men's fashion", group: "Fashion", keywords: ["men", "gents", "male"] },
  "womens-fashion": { icon: Venus, label: "Women's fashion", group: "Fashion", keywords: ["women", "ladies", "female", "dresses"] },
  "unstitched-fabric": { icon: Spool, label: "Unstitched fabric", group: "Fashion", keywords: ["lawn", "cloth", "suits", "textile", "thread"] },
  "tailoring": { icon: Scissors, label: "Tailoring", group: "Fashion", keywords: ["stitching", "alterations", "sewing"] },
  "footwear": { icon: Footprints, label: "Footwear", group: "Fashion", keywords: ["shoes", "sandals", "chappal", "sneakers", "khussa"] },
  "handbags": { icon: Handbag, label: "Handbags", group: "Fashion", keywords: ["purse", "clutch", "bags"] },
  "bags": { icon: Backpack, label: "Bags & backpacks", group: "Fashion", keywords: ["school bag", "backpack", "travel bag"] },
  "eyewear": { icon: Glasses, label: "Eyewear", group: "Fashion", keywords: ["sunglasses", "glasses", "spectacles", "optical"] },

  // Watches & jewellery
  "watches": { icon: Watch, label: "Watches", group: "Watches & jewellery", keywords: ["wristwatch", "analog", "smartwatch", "men's watches", "women's watches"] },
  "wall-clocks": { icon: Clock, label: "Wall clocks", group: "Watches & jewellery", keywords: ["clock", "time", "home clock"] },
  "alarm-clocks": { icon: AlarmClock, label: "Alarm clocks", group: "Watches & jewellery", keywords: ["table clock", "bedside", "alarm"] },
  "sports-watches": { icon: Timer, label: "Sports watches & timers", group: "Watches & jewellery", keywords: ["stopwatch", "digital", "fitness watch", "timer"] },
  "classic-timepieces": { icon: Hourglass, label: "Classic timepieces", group: "Watches & jewellery", keywords: ["vintage", "antique", "heritage", "collectible"] },
  "luxury": { icon: Crown, label: "Luxury", group: "Watches & jewellery", keywords: ["premium", "designer", "branded"] },
  "jewellery": { icon: Diamond, label: "Jewellery", group: "Watches & jewellery", keywords: ["jewelry", "rings", "necklace", "earrings", "bangles", "gold", "silver"] },
  "gemstones": { icon: Gem, label: "Gemstones", group: "Watches & jewellery", keywords: ["stones", "gems", "precious"] },
  "fine-jewellery": { icon: Sparkles, label: "Bridal & fine jewellery", group: "Watches & jewellery", keywords: ["bridal", "wedding", "fine jewelry", "sets"] },

  // Grocery & kitchen
  "groceries": { icon: ShoppingBasket, label: "Groceries", group: "Grocery & kitchen", keywords: ["kiryana", "grocery", "supermarket", "daily essentials"] },
  "fruit": { icon: Apple, label: "Fruit", group: "Grocery & kitchen", keywords: ["fresh fruit", "mango", "banana", "apple"] },
  "vegetables": { icon: Carrot, label: "Vegetables", group: "Grocery & kitchen", keywords: ["sabzi", "fresh", "greens", "veg"] },
  "dry-fruit": { icon: Nut, label: "Dry fruit & nuts", group: "Grocery & kitchen", keywords: ["almonds", "pistachio", "dates", "khajoor", "nuts"] },
  "dairy": { icon: Milk, label: "Dairy & milk", group: "Grocery & kitchen", keywords: ["milk", "yogurt", "dahi", "cheese", "butter"] },
  "eggs": { icon: Egg, label: "Eggs", group: "Grocery & kitchen", keywords: ["anday", "breakfast"] },
  "grains": { icon: Wheat, label: "Atta, rice & grains", group: "Grocery & kitchen", keywords: ["flour", "atta", "rice", "chawal", "wheat", "cereal"] },
  "pulses": { icon: Bean, label: "Daal & pulses", group: "Grocery & kitchen", keywords: ["lentils", "daal", "chana", "beans"] },
  "spices": { icon: Flame, label: "Spices & masala", group: "Grocery & kitchen", keywords: ["masala", "chilli", "herbs", "seasoning"] },
  "cooking-oil": { icon: Amphora, label: "Cooking oil & ghee", group: "Grocery & kitchen", keywords: ["oil", "ghee", "olive oil", "banaspati"] },
  "meat": { icon: Beef, label: "Meat", group: "Grocery & kitchen", keywords: ["beef", "mutton", "gosht", "halal"] },
  "poultry": { icon: Drumstick, label: "Chicken & poultry", group: "Grocery & kitchen", keywords: ["chicken", "murgh", "poultry"] },
  "seafood": { icon: Fish, label: "Fish & seafood", group: "Grocery & kitchen", keywords: ["fish", "prawns", "seafood"] },
  "bakery": { icon: Croissant, label: "Bakery", group: "Grocery & kitchen", keywords: ["bread", "rusk", "buns", "baked"] },
  "sweets": { icon: CakeSlice, label: "Mithai & desserts", group: "Grocery & kitchen", keywords: ["mithai", "cake", "dessert", "sweets"] },
  "snacks": { icon: Popcorn, label: "Snacks", group: "Grocery & kitchen", keywords: ["chips", "nimko", "biscuits", "namkeen"] },
  "tea-coffee": { icon: Coffee, label: "Tea & coffee", group: "Grocery & kitchen", keywords: ["chai", "tea", "coffee", "green tea"] },
  "beverages": { icon: CupSoda, label: "Drinks & juices", group: "Grocery & kitchen", keywords: ["soft drinks", "juice", "water", "beverages"] },
  "frozen-food": { icon: Snowflake, label: "Frozen food", group: "Grocery & kitchen", keywords: ["frozen", "ice cream", "nuggets", "parathas"] },
  "cookware": { icon: CookingPot, label: "Cookware", group: "Grocery & kitchen", keywords: ["pots", "pans", "handi", "pressure cooker"] },
  "dining": { icon: Utensils, label: "Cutlery & dining", group: "Grocery & kitchen", keywords: ["cutlery", "plates", "dinner set", "crockery"] },
  "kitchen-tools": { icon: ChefHat, label: "Kitchen tools", group: "Grocery & kitchen", keywords: ["utensils", "baking", "kitchen accessories"] },

  // Home
  "furniture": { icon: Sofa, label: "Furniture", group: "Home", keywords: ["sofa", "table", "chairs", "living room"] },
  "bedding": { icon: BedDouble, label: "Bedding", group: "Home", keywords: ["bed sheets", "pillows", "razai", "blanket", "bedroom"] },
  "lighting": { icon: Lamp, label: "Lighting", group: "Home", keywords: ["lamps", "lights", "bulbs", "led"] },
  "home-decor": { icon: Frame, label: "Home decor", group: "Home", keywords: ["decor", "wall art", "frames", "decoration"] },
  "cleaning": { icon: BrushCleaning, label: "Cleaning supplies", group: "Home", keywords: ["detergent", "mop", "cleaning", "household"] },
  "appliances": { icon: WashingMachine, label: "Home appliances", group: "Home", keywords: ["washing machine", "fridge", "microwave", "iron", "appliances"] },
  "fans-cooling": { icon: Fan, label: "Fans & cooling", group: "Home", keywords: ["fan", "air cooler", "ac", "cooling"] },
  "tools": { icon: Wrench, label: "Tools & hardware", group: "Home", keywords: ["hardware", "drill", "repair", "diy"] },
  "garden": { icon: Sprout, label: "Garden & plants", group: "Home", keywords: ["plants", "seeds", "gardening", "pots"] },

  // Electronics
  "mobile-phones": { icon: Smartphone, label: "Mobile phones", group: "Electronics", keywords: ["phones", "smartphone", "mobile", "android", "iphone"] },
  "tablets": { icon: Tablet, label: "Tablets", group: "Electronics", keywords: ["ipad", "tab"] },
  "laptops": { icon: Laptop, label: "Laptops & computers", group: "Electronics", keywords: ["laptop", "computer", "pc", "notebook"] },
  "tv": { icon: Tv, label: "TV & video", group: "Electronics", keywords: ["television", "led tv", "smart tv"] },
  "audio": { icon: Headphones, label: "Headphones & audio", group: "Electronics", keywords: ["earbuds", "headphones", "speakers", "audio"] },
  "cameras": { icon: Camera, label: "Cameras", group: "Electronics", keywords: ["camera", "photography", "dslr"] },
  "gaming": { icon: Gamepad2, label: "Gaming", group: "Electronics", keywords: ["games", "console", "playstation", "controller"] },
  "chargers": { icon: BatteryCharging, label: "Chargers & power banks", group: "Electronics", keywords: ["charger", "power bank", "battery", "cables"] },
  "electrical": { icon: Plug, label: "Electrical", group: "Electronics", keywords: ["switches", "wiring", "ups", "solar", "extension"] },

  // Beauty & health
  "makeup": { icon: Palette, label: "Makeup", group: "Beauty & health", keywords: ["cosmetics", "lipstick", "beauty"] },
  "skincare": { icon: Droplets, label: "Skincare", group: "Beauty & health", keywords: ["cream", "serum", "face wash", "lotion"] },
  "fragrance": { icon: Flower2, label: "Fragrance", group: "Beauty & health", keywords: ["perfume", "attar", "body spray", "scent"] },
  "personal-care": { icon: SoapDispenserDroplet, label: "Personal care", group: "Beauty & health", keywords: ["soap", "shampoo", "hygiene", "hair care"] },
  "health": { icon: HeartPulse, label: "Health & wellness", group: "Beauty & health", keywords: ["wellness", "medical", "fitness"] },
  "medicines": { icon: Pill, label: "Medicines", group: "Beauty & health", keywords: ["pharmacy", "medicine", "tablets"] },
  "supplements": { icon: PillBottle, label: "Vitamins & supplements", group: "Beauty & health", keywords: ["vitamins", "protein", "nutrition"] },

  // Kids & baby
  "baby": { icon: Baby, label: "Baby care", group: "Kids & baby", keywords: ["diapers", "baby", "infant", "newborn"] },
  "toys": { icon: ToyBrick, label: "Toys", group: "Kids & baby", keywords: ["toys", "kids", "play"] },
  "puzzles": { icon: Puzzle, label: "Puzzles & games", group: "Kids & baby", keywords: ["puzzle", "board games"] },
  "learning-toys": { icon: Blocks, label: "Learning toys", group: "Kids & baby", keywords: ["educational", "blocks", "montessori"] },
  "school-supplies": { icon: PencilRuler, label: "School supplies", group: "Kids & baby", keywords: ["school", "pencils", "geometry box"] },

  // Sports & outdoors
  "fitness": { icon: Dumbbell, label: "Fitness & gym", group: "Sports & outdoors", keywords: ["gym", "workout", "weights", "exercise"] },
  "cycling": { icon: Bike, label: "Cycling", group: "Sports & outdoors", keywords: ["bicycle", "cycle", "bike"] },
  "sports": { icon: Volleyball, label: "Sports", group: "Sports & outdoors", keywords: ["cricket", "football", "hockey", "badminton", "ball"] },
  "camping": { icon: Tent, label: "Camping & outdoor", group: "Sports & outdoors", keywords: ["outdoor", "hiking", "tent"] },
  "fishing": { icon: FishingRod, label: "Fishing", group: "Sports & outdoors", keywords: ["fishing rod", "angling"] },
  "travel": { icon: Luggage, label: "Travel & luggage", group: "Sports & outdoors", keywords: ["suitcase", "luggage", "travel"] },

  // General
  "general": { icon: Tag, label: "General", group: "General", keywords: ["tag", "all", "products", "misc"] },
  "featured": { icon: Star, label: "Featured", group: "General", keywords: ["best sellers", "popular", "top"] },
  "sale": { icon: Percent, label: "Sale", group: "General", keywords: ["discount", "offers", "deals", "clearance"] },
  "bundles": { icon: Package, label: "Bundles", group: "General", keywords: ["package", "box", "combo", "deal"] },
  "gifts": { icon: Gift, label: "Gifts", group: "General", keywords: ["gift", "eid", "present", "hampers"] },
  "party": { icon: PartyPopper, label: "Party supplies", group: "General", keywords: ["party", "birthday", "decorations", "balloons"] },
  "books": { icon: BookOpen, label: "Books", group: "General", keywords: ["books", "novels", "reading", "islamic books"] },
  "stationery": { icon: NotebookPen, label: "Stationery", group: "General", keywords: ["notebooks", "pens", "office", "paper"] },
  "pets": { icon: PawPrint, label: "Pet supplies", group: "General", keywords: ["pets", "cat", "dog", "pet food"] },
  "car-accessories": { icon: CarFront, label: "Car accessories", group: "General", keywords: ["auto", "car", "motorbike", "vehicle"] },
} as const;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export function isCategoryIconKey(v: unknown): v is CategoryIconKey {
  return typeof v === "string" && Object.prototype.hasOwnProperty.call(CATEGORY_ICONS, v);
}
